In [3]:
import numpy as np

In [5]:
data1=[6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
arr1.dtype

dtype('float64')

In [12]:
arr12 = np.array(data1, dtype=np.int32)
arr12

array([6, 7, 8, 0, 1])

In [13]:
arr12.dtype

dtype('int32')

In [6]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.shape

(2, 4)

In [15]:
arr=np.array([[1.,2.,3.], [4.,5.,6.]])
print('\n',arr)
print('\n',arr*arr)
print('\n',arr-arr)
print('\n',1/arr)
print('\n',arr**0.5)



 [[1. 2. 3.]
 [4. 5. 6.]]

 [[ 1.  4.  9.]
 [16. 25. 36.]]

 [[0. 0. 0.]
 [0. 0. 0.]]

 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [17]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
print('\n', arr2)
print('\n',arr2 > arr)


 [[ 0.  4.  1.]
 [ 7.  2. 12.]]

 [[False  True False]
 [ True False  True]]


In [18]:
arr = np.arange(10)
print('\n', arr[5])
print('\n', arr[5:8])


 5

 [5 6 7]


In [20]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [27]:
np.random.seed(12345)
names = np.array(['Jo', 'Seung', 'Hyeon','Jo', 'Seung', 'Hyeon','Jo'])
data = np.random.randn(7,4)
print('\n', names, "\n")
print('\n', data)

print('\n',names=='Jo')
print('\n',data[names=='Jo'])
print('\n',data[names=='Jo', 2:])
print('\n',data[names=='Jo', 3])



 ['Jo' 'Seung' 'Hyeon' 'Jo' 'Seung' 'Hyeon' 'Jo'] 


 [[-0.20470766  0.47894334 -0.51943872 -0.5557303 ]
 [ 1.96578057  1.39340583  0.09290788  0.28174615]
 [ 0.76902257  1.24643474  1.00718936 -1.29622111]
 [ 0.27499163  0.22891288  1.35291684  0.88642934]
 [-2.00163731 -0.37184254  1.66902531 -0.43856974]
 [-0.53974145  0.47698501  3.24894392 -1.02122752]
 [-0.5770873   0.12412128  0.30261356  0.52377207]]

 [ True False False  True False False  True]

 [[-0.20470766  0.47894334 -0.51943872 -0.5557303 ]
 [ 0.27499163  0.22891288  1.35291684  0.88642934]
 [-0.5770873   0.12412128  0.30261356  0.52377207]]

 [[-0.51943872 -0.5557303 ]
 [ 1.35291684  0.88642934]
 [ 0.30261356  0.52377207]]

 [-0.5557303   0.88642934  0.52377207]
